package com.example.dt.List_Test.Model;

import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;

@androidx.room.Dao
public interface CoursesDao {

    @Insert
    void Insert(Course course);

    @Update
    void Update(Course course);

    @Delete
    void Delete(Course course);

    @Query("Delete from course_table ")
    void DeleteAll();

    @Query("Select * from course_table where _Autogenerated > :Last order by _Autogenerated limit 10 ")
    List<Course> GeteAll(int Last);

    @Query("Select * from course_table where id not in(:integers)  order by _Autogenerated limit 10 ")
    List<Course> GeteAllExceptthis(List<Integer> integers);


}
