package com.example.dt.List_Test.Model;

import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import com.google.gson.annotations.SerializedName;

@Entity(tableName = "course_table", indices = @Index(value = {"id"}, unique = true))
public class Course {

    @PrimaryKey(autoGenerate = true)
    private int _Autogenerated;

    int id;

    @SerializedName("full_name")
    String Name;

    @SerializedName("description")
    String Desc;

    @SerializedName("html_url")
    String Link;

    public Course(String Name, String Desc, String Link) {
        this.Name = Name;
        this.Desc = Desc;
        this.Link = Link;
    }

    public void set_Autogenerated(int _Autogenerated) {
        this._Autogenerated = _Autogenerated;
    }

    public int get_Autogenerated() {
        return _Autogenerated;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public String getDesc() {
        return Desc;
    }

    public String getLink() {
        return Link;
    }
}
